# Generated by Django 3.1.2 on 2021-02-25 04:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_service', models.CharField(editable=False, max_length=20)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('retry_number', models.IntegerField(default=0)),
                ('was_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandlerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler_name', models.CharField(max_length=60)),
                ('error_message', models.TextField()),
                ('event_type', models.CharField(max_length=60)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
